### ISSUE TITLE
MMD Orespawn still spawns ores despite configs

### ISSUE THREAD

**Issue by breadguyyy** [MinecraftModDevelopmentMods/MMDLib#39]
I set using_orespawn and fallback_orespawn to false in the MMDlib config, but MMD OreSpawn still generates ores ingame. ive tried removing MMD OreSpawn but when i do, other ore generation mods wont generate base metal ores. this one has been a mystery for a while to me, ive tried both Ore Stone Variants and Realistic Ore Veins and configured them both properly. Makes less sense to me because OSV spawns its own variants of the ores in world, so idk how orespawn could be affecting that.

thanks for putting up with my constant problems i seem to be causing with your mods lol

**Comment by dshadowwolf** [comment]
-ERR_NOT_A_BUG

MMD OreSpawn has its own configuration and is ***NOT*** controlled by MMDLib. If you have turned off "using_orespawn" and related in MMDLib and others and are not using MMD OreSpawn at all, you can get rid of it entirely. Otherwise you can just get rid of the json's from ``config/orespawn3`` as long as you leave the ``sysconf`` directory alone.
