### ISSUE TITLE
Crash on server Startup using rc2

### ISSUE THREAD

**Issue by FatherKonrad** [MinecraftModDevelopmentMods/MMDLib#40]
The crash only happens when I start up my modded server. The client starts fine with the same mods. I think I might know what the issue is (Java doesn't  recognize "," as a decimal point) but since this was supposed to be fixed i rc2 I thought bringing it to your attention might be a good idea.

[crash-2019-05-25_21.43.40-server.txt](https://github.com/MinecraftModDevelopmentMods/MMDLib/files/3220281/crash-2019-05-25_21.43.40-server.txt)

**Comment by dshadowwolf** [comment]
oh, ffs - I missed that and one other spot where, early on, I'd relied on Java having all that internationalization and got bit by it. Thanks for the report - will be fixed in -rc3 and there is a workaround over in the BaseMetals closed issues...

Try starting the server with (on Unix/Linux):
```
LOCALE=EN_US <java command>
```
Or, on Windows, by setting the "Locale" environment variable in a similar manner

**Comment by FatherKonrad** [comment]
How do I set the locale environment variable on windows?

**Comment by FatherKonrad** [comment]
I figured it out and it worked (looked at the closed issue over at BaseMetals), thanks for the help!
